apiVersion: v1
kind: ConfigMap
metadata:
  name: ${APP_KEY}-cfgmap-logback
  namespace: ${APP_KUB_NAMESPACE}
  labels:
    app: ${APP_KEY} # tag with the app:demo10, labels are kind of like tags
data:
  logback.groovy: |+
    scan("5 seconds")
    println "#### using kubernetes ${APP_KEY}-cfgmap-logback for logback config"
    appender('STDOUT', ConsoleAppender) {
        encoder(PatternLayoutEncoder) {
            charset = java.nio.charset.Charset.forName('UTF-8')
            pattern = '%d{HH:mm:ss.SSS} [%t] %-5level %logger{48} - %msg%n'
        }
    }
    root(ERROR, ['STDOUT'])
    logger("grails.app", INFO, ['STDOUT'], false)
    logger("nine", INFO, ['STDOUT'], false)
